# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5309ad1908bdf89670ab8f23ed82f6d8428b3e73edf67c0d26b9f87c5cffc3e272047f1babb42cddd9de42f1a6e16a19d693a6633319b06b5fde216dbf2a8ea8

test:
  secret_key_base: 96269bd9bfa72900bb0aad9c846125f5ea777dde05da1f37ddf123c9c4c525e49286e31f33f500dc4a61301955f340eda4064fe5c6da1bf4e884e5ecf0d9737f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
